#!/bin/bash

gzip -dk ${1::-7}_mc.nii.gz
rest_mc=${1::-7}_mc.nii
DIR_rs=$(dirname $rest_mc)


matlab -nodisplay -r "m08_tsnr_detrend('"$rest_mc"', '"$DIR_rs"/temp_detrend.nii'); quit"
echo Detrend Done!

# === Compute tSNR
sct_fmri_compute_tsnr -i $DIR_rs/temp_detrend.nii \
  -o ${rest_mc::-4}_tsnr.nii.gz


# === Overlay _tSNR with _msc
sct_maths -i ${rest_mc::-4}_tsnr.nii.gz \
  -mul ${rest_mc::-4}_mean_msc_man.nii.gz \
  -o $DIR_rs/temp_detrend_tsnr_msc.nii

matlab -nodisplay -r "m08_tsnr('"$DIR_rs/temp_detrend_tsnr_msc.nii"', '"${rest_mc::-4}_tsnr_slice.txt"'); quit"


# === Calculate Mean tSNR from _detrend_msc
fslstats $DIR_rs/temp_detrend_tsnr_msc.nii \
  -n -M > ${rest_mc::-4}_tsnr.txt


# === Overlay _tSNR with _msc eroded by 1
sct_maths \
  -i ${rest_mc::-4}_mean_msc_man.nii.gz \
  -erode 1 -shape disk -dim 2 \
  -o ${rest_mc::-4}_mean_msc_man_ero1.nii.gz

sct_maths -i ${rest_mc::-4}_tsnr.nii.gz \
  -mul ${rest_mc::-4}_mean_msc_man_ero1.nii.gz \
  -o $DIR_rs/temp_detrend_tsnr_msc_ero1.nii

matlab -nodisplay -r "m08_tsnr('"$DIR_rs/temp_detrend_tsnr_msc_ero1.nii"', '"${rest_mc::-4}_tsnr_slice_ero1.txt"'); quit"


# === Calculate Mean tSNR from _detrend_msc_ero1
fslstats $DIR_rs/temp_detrend_tsnr_msc_ero1.nii \
  -n -M > ${rest_mc::-4}_tsnr_ero1.txt


rm $DIR_rs/temp*
rm $rest_mc


# === Copy tSNR files to a centralized folder for easy analysis
func_mean=${1::-7}_mc_mean.nii.gz
directory=$(dirname $(dirname $(dirname $(dirname $(dirname $(dirname $func_mean))))))
subject=$(basename $(dirname $(dirname $(dirname $(dirname $func_mean)))))
session=$(basename $(dirname $(dirname $(dirname $func_mean))))

DIR_tsnr=$directory/04_Results/08_sublvl_tsnr

mkdir -p $DIR_tsnr
rm $DIR_tsnr/${subject}_${session}*

cp ${rest_mc::-4}_tsnr_slice.txt $DIR_tsnr/${subject}_${session}_rs_cr_mc_tsnr_slice.txt
cp ${rest_mc::-4}_tsnr.txt $DIR_tsnr/${subject}_${session}_rs_cr_mc_tsnr.txt
cp ${rest_mc::-4}_tsnr_slice_ero1.txt $DIR_tsnr/${subject}_${session}_rs_cr_mc_tsnr_slice_ero1.txt
cp ${rest_mc::-4}_tsnr_ero1.txt $DIR_tsnr/${subject}_${session}_rs_cr_mc_tsnr_ero1.txt
