#!/bin/bash

DIR=$1
subject=$2
session=$3


DIR_sub=$DIR/03_Processing/${subject}/sublvl_megre_zstat1
DIR_results=$DIR/04_Results/20_sublvl_megre_zstat1/${subject}

mkdir -vp $DIR_results


sct_crop_image \
  -i $DIR_sub/${subject}_${session}_anat_cr_mc.nii.gz \
  -xmin 15 -xmax 82 \
  -ymin 15 -ymax 82 \
  -o $DIR_results/${subject}_${session}_anat_cr_mc.nii.gz
