#!/bin/bash
# directory=$1
# run_min=$2
# num_sub=$3

cd $(dirname $0)

DIR=/media/neuroimaging/SSD_ChK/lumbar_fMRI/14_LTR
# run_min=4run_10min
# num_sub=25

pathRando=${DIR}/03_Processing/grplvl_randomise
pathSubData=${pathRando}/25of25sub/4run_10min
rm -rv $pathSubData/ses-diff_*

# ------------------------------------------------------------------------------
# Concatenate copes from the sessions into one file
cope_ses01=$pathSubData/ses-01_25sub-all_4run_10min_cope1_cr.nii.gz
cope_ses02=$pathSubData/ses-01_25sub-all_4run_10min_cope1_cr.nii.gz
cope_all=$pathSubData/ses-diff_25sub-all_4run_10min_cope1_cr.nii.gz

sct_image \
  -i $cope_ses01 $cope_ses02 \
  -concat t \
  -o $cope_all

# ------------------------------------------------------------------------------
# Run FSL randomise
design_mat=m22_fslrandomise_difference_design.mat
design_con=m22_fslrandomise_difference_design.con
design_grp=m22_fslrandomise_difference_design.grp
mask=${pathRando}/PAM50_cord_cr.nii.gz

randomise_parallel \
  -i ${cope_all} \
  -o ${cope_all::-16} \
  -d ${design_mat} -t ${design_con} -e ${design_grp} \
  -m $mask \
  -v 5 -T

rm -rv ${pathSubData}/ses-diff_*logs
rm -rv ${pathSubData}/ses-diff_*defragment
rm -rv ${pathSubData}/ses-diff_*generate

# ------------------------------------------------------------------------------
#  Crop results into the 04_Results folder
pathRes=$DIR/04_Results/21_grplvl_randomise/25of25sub/4run_10min

nameRes1=ses-diff_25of25sub_01-02_4run_10min
sct_crop_image \
  -i ${cope_all::-16}_tstat1.nii.gz \
  -xmin 20 -xmax 50 \
  -ymin 20 -ymax 50 \
  -o ${pathRes}/${nameRes1}_tstat1_cr.nii

sct_crop_image \
  -i ${cope_all::-16}_tfce_corrp_tstat1.nii.gz \
  -xmin 20 -xmax 50 \
  -ymin 20 -ymax 50 \
  -o ${pathRes}/${nameRes1}_tfce_corrp_tstat1_cr.nii

nameRes2=ses-diff_25of25sub_02-01_4run_10min
sct_crop_image \
  -i ${cope_all::-16}_tstat2.nii.gz \
  -xmin 20 -xmax 50 \
  -ymin 20 -ymax 50 \
  -o ${pathRes}/${nameRes2}_tstat2_cr.nii

sct_crop_image \
  -i ${cope_all::-16}_tfce_corrp_tstat2.nii.gz \
  -xmin 20 -xmax 50 \
  -ymin 20 -ymax 50 \
  -o ${pathRes}/${nameRes2}_tfce_corrp_tstat2_cr.nii
