#!/bin/bash

DIR=$1

DIR_90=$DIR/90_neuro_segm
rm -rf $DIR_90
mkdir -vp $DIR_90

PAM50_neuro=$SCT_DIR/data/PAM50/template/PAM50_spinal_levels.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment L1 (21)
sct_maths -i $PAM50_neuro -thr 21 -uthr 21 -o $DIR_90/PAM50_neuro_L1.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_L1.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_L1.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment L2 (22)
sct_maths -i $PAM50_neuro -thr 22 -uthr 22 -o $DIR_90/PAM50_neuro_L2.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_L2.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_L2.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment L3 (23)
sct_maths -i $PAM50_neuro -thr 23 -uthr 23 -o $DIR_90/PAM50_neuro_L3.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_L3.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_L3.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment L4 (24)
sct_maths -i $PAM50_neuro -thr 24 -uthr 24 -o $DIR_90/PAM50_neuro_L4.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_L4.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_L4.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment L5 (25)
sct_maths -i $PAM50_neuro -thr 25 -uthr 25 -o $DIR_90/PAM50_neuro_L5.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_L5.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_L5.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment S1 (26)
sct_maths -i $PAM50_neuro -thr 26 -uthr 26 -o $DIR_90/PAM50_neuro_S1.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_S1.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_S1.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment S2 (27)
sct_maths -i $PAM50_neuro -thr 27 -uthr 27 -o $DIR_90/PAM50_neuro_S2.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_S2.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_S2.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment S3 (28)
sct_maths -i $PAM50_neuro -thr 28 -uthr 28 -o $DIR_90/PAM50_neuro_S3.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_S3.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_S3.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment S4 (29)
sct_maths -i $PAM50_neuro -thr 29 -uthr 29 -o $DIR_90/PAM50_neuro_S4.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_S4.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_S4.nii.gz

#-------------------------------------------------------------------------------
# Create binary mask for neurological segment S5 (30)
sct_maths -i $PAM50_neuro -thr 30 -uthr 30 -o $DIR_90/PAM50_neuro_S5.nii.gz
sct_maths -i $DIR_90/PAM50_neuro_S5.nii.gz -bin 1 -o $DIR_90/PAM50_neuro_S5.nii.gz
