#!/bin/bash

threshold=0.95

path=

path1=${path}/25of25sub/4run_10min/ses-01_25of25sub-mean_4run_10min_tfce_corrp_tstat1_cr.nii
path2=${path}/25of25sub/2run_6min/ses-01_25of25sub-mean_2run_6min_tfce_corrp_tstat1_cr.nii

sct_maths \
  -i ${path1} \
  -bin ${threshold} \
  -o ${path}/temp_1.nii.gz

sct_maths \
  -i ${path2} \
  -bin ${threshold} \
  -o ${path}/temp_2.nii.gz

sct_dice_coefficient \
  -i ${path}/temp_1.nii.gz \
  -d ${path}/temp_2.nii.gz \
  -o ${path}/temp_res.txt

rm -v ${path}/temp*
